version: "3"
services:

  web:
    image: nginx:1.14.1-alpine
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
        read_only: true
        volume:
          nocopy: true
      - type: volume
        source: ./nginx/html
        target: /usr/share/nginx/html
        volume:
          nocopy: true
      - type: volume
        source: ./nginx/logs
        target: /var/log/nginx
        volume:
          nocopy: true
    tmpfs:
      - /tmp