version: "3.2"
services:

  proxy:
    image: nginx:1.14.1-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
        read_only: true
        volume:
          nocopy: true
      - type: bind
        source: ./nginx/html
        target: /usr/share/nginx/html
        volume:
          nocopy: true
      - type: volume
        source: nginx_logs
        target: /var/log/nginx
        volume:
          nocopy: true
    tmpfs:
      - /tmp

volumes:
  nginx_logs:
