version: "3.2"

services:
  proxy:
    build: ./
    container_name: nginx-proxy
    restart: always
    networks:
      proxy:
        aliases:
          - nginx-proxy-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: /data/cert/dh-param/dhparam-2048.pem
        target: /etc/ssl/certs/dhparam-2048.pem
        read_only: true
        volume:
          nocopy: true
      - type: bind
        source: /data/cert/letsencrypt/etc/live
        target: /etc/nginx/certs
        read_only: true
        volume:
          nocopy: true
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
        read_only: true
        volume:
          nocopy: true
      - type: bind
        source: ./nginx/html
        target: /usr/share/nginx/html
        volume:
          nocopy: true
      - type: volume
        source: nginx_logs
        target: /var/log/nginx
        volume:
          nocopy: true
    tmpfs:
      - /tmp

volumes:
  nginx_logs:

networks:
  proxy:
    external: true
